language: python
python:
- '2.7'
install:
- pip install -r requirements.txt
# - pip install codecov
# script:
# - python manage.py test
# - coverage run --source='.' manage.py test
# after_success:
# - coveralls
# - codecov
deploy:
  matrix:
  provider: heroku
  app: upendra243-superlists
  api_key:
    secure: 6BmLLYa91YgNOU7XcOtp1/aZZWsDg1uQNS5dYzNbEZLH76BYyNA9oIoYaJa8MUiNHwCP7OLP/aaD2joCDZDvIMdWuNjqMT8WK0cJQ3v9DDYOrHoYuV6wxEzNekrOtgT9Nbqpne+9rrWw2Z6c8qJpsXHx+qeocOjFHxlJUndpHlGU2D2iLg4Po05UIqadinLXrTewSiTYhneRf6DEGbE2l5985iRraLQO+PWwl6V9nTaFpd3gqpHlzztKJl96Szabd5EsbFNVeLaFD1L8+NQd2USIZR0IfCW7JKJToajylfrAopby7xA3YwftJ0nITtDe7JomKOvfkr2reRad0uHIBG75k8FLoKk6cFJhfv9CAYdceBSZJ/e6TdNiEavNStlX6Btft9mTKIjDJbnEofESe5fnGe27N01BXhP96rAxSZUDqz4sD6PsytaKGgDKFbtMsoRvzbq3imQV8UeWGmApBYmo1tviEW1noYnIghPgUgtJ1TW44NVj0CVB4BNw52Ig1D66iAIOPbtDknfCXR4IdMhu+pa7Z2sZO+BJzglt0xRgNsTLEV3wS4cCLEbjWAMLQ7MuV66eq56cKPPOv3IF2tHpr7yWd6PzpjZcd47hfBqXr6JVo9gLjhvqhflRdTVZ93BpOnpMttm9apPGnMqThTC0iA7ru+hBJgjnLLa22Lw=
  run: "python manage.py migrate --noinput"